import type { Escort, Order, Review } from "@/lib/types";

export const services = [
  { value: "escort", label: "三角洲行动护航", price: 68 },
  { value: "evacuation", label: "三角洲行动带撤离", price: 88 },
  { value: "materials", label: "战备物资护送", price: 108 },
  { value: "rank", label: "排位上分护航", price: 58 },
  { value: "fun", label: "娱乐陪玩", price: 39 },
] as const;

export const escorts: Escort[] = [
  {
    id: "escort-001",
    user_id: "user-101",
    nickname: "夜枭",
    avatar: null,
    rank: "烽火地带王牌",
    kd: 4.8,
    price: 88,
    bio: "主打航天基地和零号大坝稳定撤离，擅长路线规划、物资保护和残局处理。",
    online_status: true,
    approved: true,
    verified: true,
    order_count: 268,
    positive_rate: 99,
    response_time: "3 分钟",
    last_active_at: "刚刚活跃",
    special_modes: ["带撤离", "物资护送"],
    special_maps: ["航天基地", "零号大坝"],
    special_playstyles: ["路线规划", "稳健转点", "语音指挥"],
    created_at: "2026-06-01T08:00:00.000Z",
  },
  {
    id: "escort-002",
    user_id: "user-102",
    nickname: "灰烬",
    avatar: null,
    rank: "钻石 I",
    kd: 3.6,
    price: 68,
    bio: "偏上分陪玩和新手教学，沟通稳定，会讲地图资源点、枪线和撤离节奏。",
    online_status: true,
    approved: true,
    verified: true,
    order_count: 154,
    positive_rate: 97,
    response_time: "5 分钟",
    last_active_at: "5 分钟前",
    special_modes: ["上分护航", "新手教学"],
    special_maps: ["长弓溪谷", "零号大坝"],
    special_playstyles: ["枪线配合", "任务推进", "节奏复盘"],
    created_at: "2026-06-02T08:00:00.000Z",
  },
  {
    id: "escort-003",
    user_id: "user-103",
    nickname: "棱镜",
    avatar: null,
    rank: "铂金 II",
    kd: 2.9,
    price: 49,
    bio: "低压沟通，适合娱乐陪玩、练枪、任务路线教学和休闲局。",
    online_status: false,
    approved: true,
    verified: true,
    order_count: 91,
    positive_rate: 95,
    response_time: "10 分钟",
    last_active_at: "今天 18:20",
    special_modes: ["娱乐陪玩", "任务教学"],
    special_maps: ["巴克什", "长弓溪谷"],
    special_playstyles: ["轻松沟通", "基础教学", "装备建议"],
    created_at: "2026-06-03T08:00:00.000Z",
  },
  {
    id: "escort-004",
    user_id: "user-104",
    nickname: "北境",
    avatar: null,
    rank: "烽火地带精英",
    kd: 5.2,
    price: 128,
    bio: "高价值物资局专长，擅长风险判断、队伍转点和撤离前清点。",
    online_status: true,
    approved: true,
    verified: true,
    order_count: 196,
    positive_rate: 98,
    response_time: "2 分钟",
    last_active_at: "在线接单",
    special_modes: ["高价值局", "物资护送"],
    special_maps: ["航天基地", "巴克什"],
    special_playstyles: ["转点指挥", "风险规避", "高价值保护"],
    created_at: "2026-06-04T08:00:00.000Z",
  },
  {
    id: "escort-005",
    user_id: "user-105",
    nickname: "赤线",
    avatar: null,
    rank: "钻石 II",
    kd: 3.9,
    price: 78,
    bio: "熟悉长弓溪谷与巴克什路线，适合任务推进、配装建议和稳定陪打。",
    online_status: true,
    approved: true,
    verified: true,
    order_count: 132,
    positive_rate: 96,
    response_time: "4 分钟",
    last_active_at: "12 分钟前",
    special_modes: ["任务推进", "上分护航"],
    special_maps: ["长弓溪谷", "巴克什"],
    special_playstyles: ["队伍配合", "配装建议", "稳健打法"],
    created_at: "2026-06-05T08:00:00.000Z",
  },
  {
    id: "escort-006",
    user_id: "user-106",
    nickname: "渡鸦",
    avatar: null,
    rank: "黄金 I",
    kd: 2.4,
    price: 39,
    bio: "娱乐局氛围型陪玩，适合新手熟悉基础操作、枪械选择和团队沟通。",
    online_status: false,
    approved: true,
    verified: false,
    order_count: 48,
    positive_rate: 94,
    response_time: "15 分钟",
    last_active_at: "昨天活跃",
    special_modes: ["娱乐陪玩", "新手练习"],
    special_maps: ["零号大坝", "长弓溪谷"],
    special_playstyles: ["轻松陪玩", "基础沟通", "练枪配合"],
    created_at: "2026-06-06T08:00:00.000Z",
  },
];

export const orders: Order[] = [
  {
    id: "order-001",
    user_id: "user-201",
    customer_id: "user-201",
    escort_id: "escort-001",
    service_type: "evacuation",
    game_mode: "烽火地带",
    requirement: "今晚 9 点后，优先带撤离，希望语音沟通。",
    price: 88,
    status: "pending",
    contact_wechat: "seed_user_201",
    contact_qq: null,
    remark: "今晚 9 点后，优先带撤离，希望语音沟通。",
    cancel_reason: null,
    cancelled_at: null,
    appointment_time: "2026-06-26T21:00:00.000Z",
    created_at: "2026-06-26T10:00:00.000Z",
  },
  {
    id: "order-002",
    user_id: "user-202",
    customer_id: "user-202",
    escort_id: "escort-002",
    service_type: "rank",
    game_mode: "排位",
    requirement: "排位上分，想顺便练习中距离对枪。",
    price: 58,
    status: "in_progress",
    contact_wechat: null,
    contact_qq: "202202",
    remark: "排位上分，想顺便练习中距离对枪。",
    cancel_reason: null,
    cancelled_at: null,
    appointment_time: "2026-06-26T20:00:00.000Z",
    created_at: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "order-003",
    user_id: "user-203",
    customer_id: "user-203",
    escort_id: "escort-004",
    service_type: "materials",
    game_mode: "航天基地",
    requirement: "仓库物资较多，目标是稳定撤离，不打无意义架。",
    price: 108,
    status: "completed",
    contact_wechat: "seed_user_203",
    contact_qq: null,
    remark: "仓库物资较多，目标是稳定撤离，不打无意义架。",
    cancel_reason: null,
    cancelled_at: null,
    completed_at: "2026-06-24T23:30:00.000Z",
    appointment_time: "2026-06-24T22:00:00.000Z",
    created_at: "2026-06-24T12:30:00.000Z",
  },
  {
    id: "order-004",
    user_id: "user-204",
    customer_id: "user-204",
    escort_id: "escort-003",
    service_type: "fun",
    game_mode: "休闲局",
    requirement: "娱乐局，熟悉地图即可。",
    price: 39,
    status: "cancelled",
    contact_wechat: "seed_user_204",
    contact_qq: null,
    remark: "娱乐局，熟悉地图即可。",
    cancel_reason: "临时改期，重新预约其他时间。",
    cancelled_at: "2026-06-23T15:20:00.000Z",
    appointment_time: "2026-06-23T21:00:00.000Z",
    created_at: "2026-06-23T11:10:00.000Z",
  },
];

export const reviews: Review[] = [
  {
    id: "review-001",
    order_id: "order-101",
    user_id: "user-301",
    escort_id: "escort-001",
    rating: 5,
    content: "路线判断很稳，撤离前会提醒补状态和检查背包，适合高价值物资局。",
    tags: ["准时", "沟通好", "技术强"],
    hidden: false,
    created_at: "2026-06-20T08:00:00.000Z",
  },
  {
    id: "review-002",
    order_id: "order-102",
    user_id: "user-302",
    escort_id: "escort-002",
    rating: 5,
    content: "讲解很清楚，适合新手熟悉资源点和撤离节奏。",
    tags: ["沟通好", "态度好"],
    hidden: false,
    created_at: "2026-06-21T08:00:00.000Z",
  },
  {
    id: "review-003",
    order_id: "order-003",
    user_id: "user-203",
    escort_id: "escort-004",
    rating: 5,
    content: "物资局非常稳，转点果断，最后成功带出高价值装备。",
    tags: ["撤离成功", "技术强"],
    hidden: false,
    created_at: "2026-06-24T23:40:00.000Z",
  },
  {
    id: "review-004",
    order_id: "order-104",
    user_id: "user-304",
    escort_id: "escort-005",
    rating: 4,
    content: "沟通舒服，任务推进效率高，适合晚上固定车队。",
    tags: ["准时", "沟通好"],
    hidden: false,
    created_at: "2026-06-22T19:00:00.000Z",
  },
];
